### ISSUE TITLE
Unhandled exception when not connected to the network

### ISSUE THREAD

**Issue by probonopd** [Chhekur/local-browser#1]
Unhandled exception when not connected to the network

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/5c04391690fe3cbe4745ee9e184d6232fa9a312d/database/Local_Browser/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1281

**Comment by Chhekur** [comment]
This issue has been fixed.
Please update Local Browser
